# Site settings
title: PONMATHI C. R.J.
email: prama008@ucr.edu
url: https://mathrj.github.io
description: "Bioinformatics Engineer"

# Color settings (hex-codes without the leading hash-tag)
color:
  primary-dark: '#000000'
  links: '#219ab3'

# Footer settings
footer: Ponmathi C. Ramasamy Jayaseelan

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: https://twitter.com/mathCRJ
  - title: linkedin
    url: https://www.linkedin.com/in/ponmathi-ramasamy-jayaseelan-0b5778171/
  - title: github
    url: https://github.com/mathrj

# Build settings
markdown: kramdown
permalink: pretty
